### PR TITLE
Disabled type annotation inspections in IntelliJ.

### PR DESCRIPTION
**Pull request by kshakir**
Synced common scala .gitignore across repositories.

### CODE REVIEW

**Comment by mcovarr** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/broadinstitute/wdltool/pull-request/21/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/wdltool)

**Comment by mcovarr** [comment]
:+1:

**Comment by ruchim** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/broadinstitute/wdltool/pull-request/21/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/wdltool)

**Comment by kshakir** [comment]
No idea why mcovarr's thumb didn't take. Can I add my own? 👍 

[Approved with PullApprove](https://pullapprove.com/broadinstitute/wdltool/pull-request/21/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/wdltool)

**Comment by mcovarr** [comment]
rethumbing :+1:

[Approved with PullApprove](https://pullapprove.com/broadinstitute/wdltool/pull-request/21/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/wdltool)

**Pull request merged**
