### PR TITLE
Bumped pullapprove to v2.

### PR DESCRIPTION
**Pull request by kshakir**
Added danbills.

### CODE REVIEW

**Comment by danbills** [comment]
:+1:

**Comment by mcovarr** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/broadinstitute/wdltool/pull-request/40/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/wdltool)

**Comment by mcovarr** [comment]
@danbills unfortunately the current system doesn't acknowledge real emoji thumbs as approvals but requires `:+1:`

**Comment by kshakir** [comment]
I think @danbills tried to approve adding himself to the pullapprove and was denied. Merging in spirit.

**Comment by mcovarr** [comment]
@kshakir oh yeah duh, you're right 😊

**Pull request merged**
